force-app/main/default/objects/Items__mdt/Items__mdt.object-meta.xml
<CustomObject>
    <label>Item</label>
    <pluralLabel>Items</pluralLabel>
</CustomObject>

force-app/main/default/objects/Items__mdt/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CMutility.cls
public class CMutility {
    
    
    public static void before(){
        List<Items__mdt> listdata =  [SELECT Id, DeveloperName, MasterLabel, Language, 
                                      NamespacePrefix, Label, QualifiedApiName, Brand__c FROM Items__mdt];
        System.debug(listdata);
    }
    
    
    public static void getalltest(){
        Map<String,Items__mdt> datalist = Items__mdt.getAll();
        System.debug(datalist);
    }
    
     public static void getInstance(String recordId){
        Items__mdt record = Items__mdt.getInstance(recordId);
        System.debug(record);
    }
    
     public static void getInstanceByLabel(String label){
        Items__mdt record = Items__mdt.getInstance(label);
        System.debug(record);
    }
    
    public static void name(){
        System.debug("hello");
    }
    
    
}